config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :emprestimos
  resources :livros
  resources :alunos
  root "bem_vindo#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    has_many :emprestimos
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all.page params[:page]
    gera_pdf(@alunos)
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if validar_dados(@aluno)
        format.html { redirect_to new_aluno_path, alert: @error }
        format.json { head :no_content }
      else
        if @aluno.save
          format.html { redirect_to @aluno, notice: 'Aluno foi cadastrado com sucesso.' }
          format.json { render :show, status: :created, location: @aluno }
        else
          format.html { render :new }
          format.json { render json: @aluno.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :matricula, :email, :telefone)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
    def validar_dados(aluno)
        #Verifica se todos os campos foram prenchido
        if aluno.nome.empty? || aluno.matricula.nil? || aluno.email.empty? || aluno.telefone.empty?
            @error = "Todos os campos devem ser preenchido." 
            true
        #Verifica se a matricula esta correta
        elsif aluno.matricula.digits.count < 7
            @error = "Matricula incorreta." 
            true
        #Verifica se o aluno já esta cadastrado
        elsif Aluno.where(matricula: aluno.matricula).exists?
            @error = "Aluno já cadastrado no sistema." 
            true
        else
            false
        end
    end

    def gera_pdf(aluno)
        respond_to do |format|
            format.html
            format.pdf do
              pdf = AlunosPdf.new(aluno)
              send_data pdf.render, type: "application/pdf", disposition: "inline"
            end
          end
    end
end

app/views/alunos/_form.html.erb
<%= form_for @aluno, :html => { :class => "form-horizontal aluno" } do |f| %>

  <% if @aluno.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @aluno.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="jumbotron" style="
      padding-left: 20px;
      padding-top: 20px;
      padding-right: 20px;
      padding-bottom: 20px;
      width: 340px;
      margin-bottom: 0px;
      ">
    <div class="form-group">
      <label for="aluno_nome">Nome:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 320px;">
        <%= f.text_field :nome, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <label for="aluno_matricula">Matricula:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.number_field :matricula, :class => "form-control", 
            :oninput => "javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);",
            :maxlength => "7" %>
      </div>
    </div>
    <div class="form-group">
      <label for="aluno_email">Email:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.text_field :email, :class => 'form-control', :placeholder => "nome@exemplo.com" %>
      </div>
    </div>
    <div class="form-group">
      <label for="aluno_telefone">Telefone:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.text_field :telefone, :class => 'form-control', :maxlength => "16", 
        :placeholder => "(00) 0-0000-0000" %>
      </div>
    </div>
    </br>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10" style="padding-left: 0px;width: 250px;margin-left: 0px">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  root_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>

<% end %>

app/views/alunos/edit.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alunos/index.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:matricula) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
    </tr>
  </thead>
  <tbody>
    <%n = 0%>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= n += 1 %></td>
        <td><%= aluno.nome %></td>
        <td><%= aluno.matricula %></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.telefone %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      aluno_path(aluno), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_aluno_path(aluno), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      aluno_path(aluno),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div><%= paginate @alunos %></div>

<%= link_to t('.back', :default => t("helpers.links.back")),
            root_path,
            :class => 'btn btn-primary' %>
<%= link_to "Gerar PDF", alunos_path(@aluno, format: "pdf"), :class => 'btn btn-warning'%>

app/views/alunos/new.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alunos/show.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt style="width: 110px;"><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
    <dd style="margin-left: 120px;"><%= @aluno.nome %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt style="width: 110px;"><strong><%= model_class.human_attribute_name(:matricula) %>:</strong></dt>
    <dd style="margin-left: 120px;"><%= @aluno.matricula %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt style="width: 110px;"><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
    <dd style="margin-left: 120px;"><%= @aluno.email %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt style="width: 110px;"><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
    <dd style="margin-left: 120px;"><%= @aluno.telefone %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt style="width: 110px;"><strong><%= model_class.human_attribute_name(:emprestimos) %>:</strong></dt>
    <% @aluno.emprestimos.each do |emprestimos|%>
        <dd style="margin-left: 120px;"><%= link_to emprestimos.livro_titulo, emprestimo_path(emprestimos)%></dd>
    <% end %>
  </div>
</dl>


<%= link_to t('.back', :default => t("helpers.links.back")),
              alunos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_aluno_path(@aluno), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              aluno_path(@aluno),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>