config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :emprestimos
  resources :livros
  resources :alunos
  root "bem_vindo#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/emprestimo.rb
class Emprestimo < ApplicationRecord
    belongs_to :aluno
    belongs_to :livro
end

app/controllers/emprestimos_controller.rb
class EmprestimosController < ApplicationController
  before_action :set_emprestimo, only: [:show, :edit, :update, :destroy]

  # GET /emprestimos
  # GET /emprestimos.json
  def index
    @emprestimos = Emprestimo.all.page params[:page]
    gerar_pdfs(@emprestimos)
  end

  # GET /emprestimos/1
  # GET /emprestimos/1.json
  def show
  end

  # GET /emprestimos/new
  def new
    @emprestimo = Emprestimo.new
  end

  # GET /emprestimos/1/edit
  def edit
  end
  
  # POST /emprestimos
  # POST /emprestimos.json
  def create
    @emprestimo = Emprestimo.new(emprestimo_params)

    respond_to do |format|
      if validar_dados(@emprestimo)
        format.html { redirect_to new_emprestimo_path, alert: @error }
        format.json { head :no_content }
      else
        finalizar_dados(@emprestimo)
        if @emprestimo.save
          format.html { redirect_to @emprestimo, notice: 'Emprestimo foi cadastrado com sucesso.' }
          format.json { render :show, status: :created, location: @emprestimo }
        else
          format.html { render :new }
          format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  # PATCH/PUT /emprestimos/1
  # PATCH/PUT /emprestimos/1.json
  def update
    respond_to do |format|
      if validar_dados(@emprestimo)
        format.html { redirect_to new_emprestimo_path, alert: @error }
        format.json { head :no_content }
      else
        finalizar_dados(@emprestimo)

        if @emprestimo.update(emprestimo_params)
          format.html { redirect_to @emprestimo, notice: 'Emprestimo foi atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @emprestimo }
        else
          format.html { render :edit }
          format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /emprestimos/1
  # DELETE /emprestimos/1.json
  def destroy
    @emprestimo.destroy
    respond_to do |format|
      format.html { redirect_to emprestimos_url, notice: 'Livro devolvido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emprestimo
      @emprestimo = Emprestimo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emprestimo_params
      params.require(:emprestimo).permit(:aluno_nome, :matricula, :livro_titulo, :codigo, :data_emprestimo, :data_devoluncao, :aluno_id, :livro_id)
    end
end

app/helpers/emprestimos_helper.rb
module EmprestimosHelper
    # Se aluno não existe não banco dados ou um livro uma messagem informativa e lançada para o usuario
    def validar_dados(emprestimo)
        if !Aluno.where(matricula: emprestimo.matricula).exists?
            @error = "Matricula incorreta ou não cadastrada." 
            true
        elsif !Livro.where(codigo: emprestimo.codigo).exists?
            @error = "Codigo incorreto ou não cadastrado." 
            true
        elsif emprestimo.data_devoluncao.nil?
            @error = "Selecione uma data para devolução." 
            true
        else
            false
        end
    end
    
    def finalizar_dados(emprestimo)
         # Pesquisa no banco da dados aluno e livro com o numero da matricula do aluno e codigo do livro 
         aluno = Aluno.where(matricula: @emprestimo.matricula).first
         livro = Livro.where(codigo: @emprestimo.codigo).first
 
         # Emprestimo aluno e livro recebe os valores do aluno nome e livro titulo e data do emprestimo receber data atual
         @emprestimo.aluno_nome = aluno.nome
         @emprestimo.livro_titulo = livro.titulo
         @emprestimo.data_emprestimo = Time.now.strftime("%Y-%m-%d")
         @emprestimo.aluno = aluno
         @emprestimo.livro = livro
    end

    def gerar_pdfs(emprestimo)
        respond_to do |format|
            format.html
            format.pdf do
              pdf = EmprestimosPdf.new(emprestimo)
              send_data pdf.render, type: "application/pdf", disposition: "inline"
            end
          end
    end
end

app/views/emprestimos/_form.html.erb
<%= form_for @emprestimo, :html => { :class => "form-horizontal emprestimo" } do |f| %>

  <% if @emprestimo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@emprestimo.errors.count, "error") %> prohibited this emprestimo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @emprestimo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :aluno, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :aluno, :class => 'form-control' %>
    </div>
    <%=f.error_span(:aluno) %>
  </div>
  <div class="form-group">
    <%= f.label :matricula, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :matricula, :class => 'form-control' %>
    </div>
    <%=f.error_span(:matricula) %>
  </div>
  <div class="form-group">
    <%= f.label :livro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :livro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:livro) %>
  </div>
  <div class="form-group">
    <%= f.label :codigo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :codigo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:codigo) %>
  </div>
  <div class="form-group">
    <%= f.label :data_emprestimo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :data_emprestimo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data_emprestimo) %>
  </div>
  <div class="form-group">
    <%= f.label :data_devoluncao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :data_devoluncao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data_devoluncao) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                emprestimos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/emprestimos/edit.html.erb
<%- model_class = Emprestimo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= form_for @emprestimo, :html => { :class => "form-horizontal emprestimo" } do |f| %>

  <% if @emprestimo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@emprestimo.errors.count, "error") %> prohibited this emprestimo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @emprestimo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="jumbotron" style="
    padding-left: 20px;
    padding-top: 20px;
    padding-right: 20px;
    padding-bottom: 20px;
    width: 360px;
    margin-bottom: 0px;
    ">

    <div class="form-group">
     <label for="emprestimo_aluno_nome">Aluno:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 300px;">
        <%= f.text_field :aluno_nome, :class => 'form-control' %>
      </div>
      <%=f.error_span(:aluno_nome) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_matricula">Matricula:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.text_field :matricula, :class => 'form-control' %>
      </div>
      <%=f.error_span(:matricula) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_livro_titulo">Livro:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 300px;">
        <%= f.text_field :livro_titulo, :class => 'form-control' %>
      </div>
      <%=f.error_span(:livro_titulo) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_codigo">Codigo:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.text_field :codigo, :class => 'form-control' %>
      </div>
      <%=f.error_span(:codigo) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_data_emprestimo">Data do emprestimo:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.date_field :data_emprestimo, :id => "datepicker" %>
      </div>
      <%=f.error_span(:data_emprestimo) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_devoluncao">Data da devolunção:</label>
      <div class="col-lg-10" style="padding-left: 0px;width: 250px;">
        <%= f.date_field :data_devoluncao, :id => "datepicker" %>
      </div>
      <%=f.error_span(:data_devoluncao) %>
    </div>

    <div class="form-group">
      <div class="">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  root_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>

<% end %>
<script>
$('#datepicker').datepicker({format: 'dd/mm/yyyy'});
</script>

app/views/emprestimos/index.html.erb
<%- model_class = Emprestimo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped ">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= model_class.human_attribute_name(:aluno) %></th>
      <th scope="col"><%= model_class.human_attribute_name(:matricula) %></th>
      <th scope="col"><%= model_class.human_attribute_name(:livro) %></th>
      <th scope="col"><%= model_class.human_attribute_name(:codigo) %></th>
      <th scope="col"><%= model_class.human_attribute_name(:data_do_emprestimo) %></th>
      <th scope="col"><%= model_class.human_attribute_name(:data_da_devolunção) %></th>
      <th scope="col">Opçoes</th>
    </tr>
  </thead>
  <tbody>
    <%n = 0%>
    <% @emprestimos.each do |emprestimo| %>
      <tr>
        <td><%= n += 1%></td>
        <td><%= link_to emprestimo.aluno_nome, aluno_path(emprestimo.aluno) %></td>
        <td><%= emprestimo.matricula %></td>
        <td><%= link_to emprestimo.livro_titulo, livro_path(emprestimo.livro) %></td>
        <td><%= emprestimo.codigo %></td>
        <td><%= l(emprestimo.data_emprestimo) %></td>
        <td><%= l(emprestimo.data_devoluncao) %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      emprestimo_path(emprestimo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_emprestimo_path(emprestimo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.devolver")),
                      emprestimo_path(emprestimo),
                      :method => :delete,
                      :data => { :confirm => "Devolver livro?" },
                      :class => 'btn btn-xs btn-success' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div><%= paginate @emprestimos %></div>


<%= link_to t('.back', :default => t("helpers.links.back")),
            root_path,
            :class => 'btn btn-primary' %>
<%= link_to "Gerar PDF", emprestimos_path(@emprestimo, format: "pdf"), :class => 'btn btn-warning'%>

app/views/emprestimos/new.html.erb
<%- model_class = Emprestimo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= form_for @emprestimo, :html => { :class => "form-horizontal emprestimo" } do |f| %>
  <% if @emprestimo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@emprestimo.errors.count, "error") %> prohibited this emprestimo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @emprestimo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="jumbotron" style="
    padding-left: 20px;
    padding-top: 20px;
    padding-right: 20px;
    padding-bottom: 20px;
    width: 340px;
    margin-bottom: 0px;
    ">
    <div class="form-group">
      <label for="emprestimo_matricula">Matricula:</label>
      <div class="col-lg-7" style="padding-left: 0px;width: 250px;">
        <%= f.number_field :matricula, :class => 'form-control' %>
      </div>
      <%=f.error_span(:matricula) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_codigo">Codigo:</label>
      <div class="col-lg-7" style="padding-left: 0px;width: 250px;">
        <%= f.text_field :codigo, :class => 'form-control' %>
      </div>
      <%=f.error_span(:codigo) %>
    </div>
    <div class="form-group">
      <label for="emprestimo_data_da_devoluncao">Data da devoluncao:</label>
      <div class="col-lg-7" style="padding-left: 0px;width: 250px;">
        <%= f.date_field :data_devoluncao, :class => 'form-control'%>
      </div>
      <%=f.error_span(:data_devoluncao) %>
    </div>
    </br>
    <div class="form-group">
      <div class="">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  root_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>

<% end %>

app/views/emprestimos/show.html.erb
<%- model_class = Emprestimo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt><strong><%= model_class.human_attribute_name(:aluno) %>:</strong></dt>
    <% aluno = @emprestimo.aluno %>
    <dd><%= link_to aluno.nome, aluno_path(aluno) %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt><strong><%= model_class.human_attribute_name(:matricula) %>:</strong></dt>
    <dd><%= @emprestimo.matricula %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt><strong><%= model_class.human_attribute_name(:livro) %>:</strong></dt>
    <% livro = @emprestimo.livro %>
    <dd><%= link_to livro.titulo, livro_path(livro) %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt><strong><%= model_class.human_attribute_name(:codigo) %>:</strong></dt>
    <dd><%= @emprestimo.codigo %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">  
    <dt><strong><%= model_class.human_attribute_name(:data_do_emprestimo) %>:</strong></dt>
    <dd><%= l(@emprestimo.data_emprestimo) %></dd>
  </div>
  <div class="jumbotron"style="
    padding-top: 10px;
    padding-left: 10px;
    padding-bottom: 10px;
    padding-right: 10px;
    margin-bottom: 20px;
">
    <dt><strong><%= model_class.human_attribute_name(:data_da_devolunção) %>:</strong></dt>
    <dd><%= l(@emprestimo.data_devoluncao) %></dd>
  </div>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              emprestimos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_emprestimo_path(@emprestimo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.devolver")),
              emprestimo_path(@emprestimo),
              :method => 'delete',
              :data => { :confirm => "Devolver livro?" },
              :class => 'btn btn-success' %>