config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :emprestimos
  resources :livros
  resources :alunos
  root "bem_vindo#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Biblioteca" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" style="
      color: #ffffff; 
      background-color: #000000;
      height: 41px;
      margin-bottom: 0px;
      border-bottom-width: 0px;
      bottom: 333px;">
      <div calss="navbar-inner">
        <div class="container" style="
        padding-left: 0px;
        padding-right: 0px;
        margin-left: 40px;
        margin-right: 40px;
        width: 1270px;
        ">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="
            padding-right: 0px;
            padding-left: 0px;
        "><img src="https://cdn.icon-icons.com/icons2/145/PNG/256/books_21468.png" class="img-fluid" style="margin-bottom: 30px;width: 30px;"></a>
          <a class="navbar-brand" href="/" style="color: #ffffff;padding-left: 0px;padding-right: 0px;">Biblioteca</a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                  <%= link_to "Emprestimos", emprestimos_path%> |
                  <%= link_to "Alunos", alunos_path %> |
                  <%= link_to "Livros", livros_path, :style => "margin-right: 695px;"%>
                  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/User_icon_2.svg/2000px-User_icon_2.svg.png" 
                  class="img-fluid" style="margin-bottom: 0px;width: 30px;"><strong><%= current_user.name %></strong>
                  <%= link_to 'Editar', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                  <%= link_to "Cadastra", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                <% end %>
              </p>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container" style="
      margin-left: 0px;
      margin-right: 0px;
      width: 1285px;
      margin-top: 70px;
      ">
      <div class="row">
        <div class="col-lg-15" >
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <hr>
      <footer>
        <p>&copy; Quero10 2018</p>
      </footer>

    </div> <!-- /container -->
    <div class="dropdown">
  </body>
</html>